name: Permission check

on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
      - 'root/migrations/*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  permission_check:
    uses: linuxserver/github-workflows/.github/workflows/init-svc-executable-permissions.yml@v1
